      PROGRAM makelayout

      IMPLICIT NONE

      character*20 fname_aux
      character*05 fname
      character*01 c1
      character*02 c2
      character*03 c3
      character*04 c4
      character*05 c5
      character*06 c6
      character*07 c7
      character*08 c8
      integer tt,my_qtimes

      fname = 'SN__S'
      my_qtimes = 1000     

      open (1,file='lay_anime.lay',access='sequential')
      write(1,'(A08)     ') '#!MC 900'
      write(1,'(A21,A1,\)') '$!VarSet |LFDSFN1| = ',char(39)

      do tt=0,500000
        if (tt.LT.10) then
          write (c1,'(I1)'),int(tt)
          fname_aux=fname//'_000000000'//c1//'.dat'
        else if (tt.LT.100) then
          write (c2,'(I2)'),int(tt)
          fname_aux=fname//'_00000000'//c2//'.dat'
         else if (tt.LT.1000) then
          write (c3,'(I3)'),int(tt)
          fname_aux=fname//'_0000000'//c3//'.dat'
         else if (tt.LT.10000) then
          write (c4,'(I4)'),int(tt)
          fname_aux=fname//'_000000'//c4//'.dat'
         else if (tt.LT.100000) then
          write (c5,'(I5)'),int(tt)
          fname_aux=fname//'_00000'//c5//'.dat'
         else if (tt.LT.1000000) then
          write (c6,'(I6)'),int(tt)
          fname_aux=fname//'_0000'//c6//'.dat'
         else if (tt.LT.10000000) then
          write (c7,'(I7)'),int(tt)
          fname_aux=fname//'_000'//c7//'.dat'
         else if (tt.LT.100000000) then
          write (c8,'(I8)'),int(tt)
          fname_aux=fname//'_00'//c8//'.dat'
        end if

        if (((mod(tt,my_qtimes).EQ.0)).AND.(tt.GT.0)) then
          write(1,'(A25,\)') '"f_'//fname_aux//'" '
          write(*,*) 'f_'//fname_aux
        end if
      end do

      write(1,'(A1)') char(39)
      write(1,*) '$!VarSet |LFDSVL1| ='//char(39)
     &  //'"x" "y" "u" "v" "wz" "rho" "p" "T" "Et"'//char(39)
      write(1,*) '$!SETSTYLEBASE FACTORY'
      write(1,*) '$!PAPER'
      write(1,*) '  BACKGROUNDCOLOR = WHITE'
      write(1,*) '  ISTRANSPARENT = YES     '                                      
      write(1,*) '  ORIENTPORTRAIT = NO'
      write(1,*) '  SHOWGRID = YES'
      write(1,*) '  SHOWRULER = YES'
      write(1,*) '  SHOWPAPER = YES'
      write(1,*) '  PAPERSIZE = LETTER'
      write(1,*) '  PAPERSIZEINFO'
      write(1,*) '    {'
      write(1,*) '    LETTER'
      write(1,*) '      {'
      write(1,*) '      WIDTH = 8.5'
      write(1,*) '      HEIGHT = 11'
      write(1,*) '      LEFTHARDCLIPOFFSET = 0.125'
      write(1,*) '      RIGHTHARDCLIPOFFSET = 0.125'
      write(1,*) '      TOPHARDCLIPOFFSET = 0.125'
      write(1,*) '      BOTTOMHARDCLIPOFFSET = 0.125'
      write(1,*) '      }'
      write(1,*) '    }'
      write(1,*) '  RULERSPACING = ONEINCH'
      write(1,*) '  PAPERGRIDSPACING = HALFINCH'
      write(1,*) '  REGIONINWORKAREA'
      write(1,*) '    {'
      write(1,*) '    X1 = -0.05'
      write(1,*) '    Y1 = -0.05'
      write(1,*) '    X2 = 11.05'
      write(1,*) '    Y2 = 8.55'
      write(1,*) '    }'
      write(1,*) '$!COLORMAP '
      write(1,*) '  CONTOURCOLORMAP = SMRAINBOW'
      write(1,*) '$!COLORMAPCONTROL RESETTOFACTORY'
      write(1,*) '### Frame Number 1 ###'
      write(1,*) '$!READDATASET  '//char(39)//'|LFDSFN1|'//char(39)
      write(1,*) '  INITIALFRAMEMODE = TWOD'
      write(1,*) '  INCLUDETEXT = NO'
      write(1,*) '  INCLUDEGEOM = NO'
      write(1,*) '  VARLOADMODE = BYNAME'
      write(1,*) '  VARNAMELIST = '//char(39)//'|LFDSVL1|'//char(39)
      write(1,*) '$!REMOVEVAR |LFDSVL1|'
      write(1,*) '$!FRAMELAYOUT '
      write(1,*) '  SHOWHEADER = NO'
      write(1,*) '  HEADERCOLOR = RED'
      write(1,*) '  XYPOS'
      write(1,*) '{'
      write(1,*) 'X = 0.059287'
      write(1,*) 'Y = 0.063043'
      write(1,*) '}'
      write(1,*) '  WIDTH = 10.84'
      write(1,*) '  HEIGHT = 8.3444'
      write(1,*) '$!FRAMEMODE  = TWOD'
      write(1,*) '$!FRAMENAME  = '//char(39)//'Frame 001'//char(39)
      write(1,*) '$!ACTIVEFIELDZONES  =  [1-4]'
      write(1,*) '$!GLOBALCONTOUR '
      write(1,*) '  VAR = 4'
      write(1,*) '  COLORCUTOFF'
      write(1,*) '{'
      write(1,*) 'RANGEMIN = 0.00162274146201'
      write(1,*) 'RANGEMAX = 0.00486825754253'
      write(1,*) '}'
      write(1,*) '  COLORMAPFILTER'
      write(1,*) '{'
      write(1,*) 'CONTINUOUSCOLOR'
      write(1,*) '  {'
      write(1,*) '  CMIN = -1.65782574953E-08'
      write(1,*) '  CMAX = 0.0064910155828'
      write(1,*) '  }'
      write(1,*) '}'
      write(1,*) '$!CONTOURLEVELS NEW'
      write(1,*) '  RAWDATA'
      write(1,*) '15'
      write(1,*) '0.000405672931809'
      write(1,*) '0.000811362441875'
      write(1,*) '0.00121705195194'
      write(1,*) '0.00162274146201'
      write(1,*) '0.00202843097207'
      write(1,*) '0.00243412048214'
      write(1,*) '0.0028398099922'
      write(1,*) '0.00324549950227'
      write(1,*) '0.00365118901234'
      write(1,*) '0.0040568785224'
      write(1,*) '0.00446256803247'
      write(1,*) '0.00486825754253'
      write(1,*) '0.0052739470526'
      write(1,*) '0.00567963656267'
      write(1,*) '0.00608532607273'
      write(1,*) '$!FIELD  [1]'
      write(1,*) '  MESH'
      write(1,*) '{'
      write(1,*) 'COLOR = RED'
      write(1,*) '}'
      write(1,*) '  CONTOUR'
      write(1,*) '{'
      write(1,*) 'CONTOURTYPE = FLOOD'
      write(1,*) 'COLOR = RED'
      write(1,*) 'USELIGHTINGEFFECT = YES'
      write(1,*) '}'
      write(1,*) '  VECTOR'
      write(1,*) '{'
      write(1,*) 'COLOR = RED'
      write(1,*) '}'
      write(1,*) '  SCATTER'
      write(1,*) '{'
      write(1,*) 'COLOR = RED'
      write(1,*) '}'
      write(1,*) '  SHADE'
      write(1,*) '{'
      write(1,*) 'COLOR = WHITE'
      write(1,*) '}'
      write(1,*) '  BOUNDARY'
      write(1,*) '{'
      write(1,*) 'COLOR = RED'
      write(1,*) '}'
      write(1,*) '  VOLUMEMODE'
      write(1,*) '{'
      write(1,*) 'VOLUMEOBJECTSTOPLOT'
      write(1,*) '  {'
      write(1,*) '  SHOWISOSURFACES = NO'
      write(1,*) '  SHOWSLICES = NO'
      write(1,*) '  SHOWSTREAMTRACES = NO'
      write(1,*) '  }'
      write(1,*) 'SURFACESTOPLOT = KPLANES'
      write(1,*) 'POINTSTOPLOT = SURFACESONLY'
      write(1,*) '}'
      write(1,*) '$!FIELD  [2]'
      write(1,*) '  MESH'
      write(1,*) '{'
      write(1,*) 'COLOR = GREEN'
      write(1,*) '}'
      write(1,*) '  CONTOUR'
      write(1,*) '{'
      write(1,*) 'CONTOURTYPE = FLOOD'
      write(1,*) 'COLOR = GREEN'
      write(1,*) 'USELIGHTINGEFFECT = YES'
      write(1,*) '}'
      write(1,*) '  VECTOR'
      write(1,*) '{'
      write(1,*) 'COLOR = GREEN'
      write(1,*) '}'
      write(1,*) '  SCATTER'
      write(1,*) '{'
      write(1,*) 'COLOR = GREEN'
      write(1,*) '}'
      write(1,*) '  SHADE'
      write(1,*) '{'
      write(1,*) 'COLOR = WHITE'
      write(1,*) '}'
      write(1,*) '  BOUNDARY'
      write(1,*) '{'
      write(1,*) 'COLOR = GREEN'
      write(1,*) '}'
      write(1,*) '  VOLUMEMODE'
      write(1,*) '{'
      write(1,*) 'VOLUMEOBJECTSTOPLOT'
      write(1,*) '  {'
      write(1,*) '  SHOWISOSURFACES = NO'
      write(1,*) '  SHOWSLICES = NO'
      write(1,*) '  SHOWSTREAMTRACES = NO'
      write(1,*) '  }'
      write(1,*) 'SURFACESTOPLOT = KPLANES'
      write(1,*) 'POINTSTOPLOT = SURFACESONLY'
      write(1,*) '}'
      write(1,*) '$!FIELD  [3]'
      write(1,*) '  MESH'
      write(1,*) '{'
      write(1,*) 'COLOR = BLUE'
      write(1,*) '}'
      write(1,*) '  CONTOUR'
      write(1,*) '{'
      write(1,*) 'CONTOURTYPE = FLOOD'
      write(1,*) 'COLOR = BLUE'
      write(1,*) 'USELIGHTINGEFFECT = YES'
      write(1,*) '}'
      write(1,*) '  VECTOR'
      write(1,*) '{'
      write(1,*) 'COLOR = BLUE'
      write(1,*) '}'
      write(1,*) '  SCATTER'
      write(1,*) '{'
      write(1,*) 'COLOR = BLUE'
      write(1,*) '}'
      write(1,*) '  SHADE'
      write(1,*) '{'
      write(1,*) 'COLOR = WHITE'
      write(1,*) '}'
      write(1,*) '  BOUNDARY'
      write(1,*) '{'
      write(1,*) 'COLOR = BLUE'
      write(1,*) '}'
      write(1,*) '  VOLUMEMODE'
      write(1,*) '{'
      write(1,*) 'VOLUMEOBJECTSTOPLOT'
      write(1,*) '  {'
      write(1,*) '  SHOWISOSURFACES = NO'
      write(1,*) '  SHOWSLICES = NO'
      write(1,*) '  SHOWSTREAMTRACES = NO'
      write(1,*) '  }'
      write(1,*) 'SURFACESTOPLOT = KPLANES'
      write(1,*) 'POINTSTOPLOT = SURFACESONLY'
      write(1,*) '}'
      write(1,*) '$!FIELD  [4]'
      write(1,*) '  MESH'
      write(1,*) '{'
      write(1,*) 'COLOR = CYAN'
      write(1,*) '}'
      write(1,*) '  CONTOUR'
      write(1,*) '{'
      write(1,*) 'CONTOURTYPE = FLOOD'
      write(1,*) 'COLOR = CYAN'
      write(1,*) 'USELIGHTINGEFFECT = YES'
      write(1,*) '}'
      write(1,*) '  VECTOR'
      write(1,*) '{'
      write(1,*) 'COLOR = CYAN'
      write(1,*) '}'
      write(1,*) '  SCATTER'
      write(1,*) '{'
      write(1,*) 'COLOR = CYAN'
      write(1,*) '}'
      write(1,*) '  SHADE'
      write(1,*) '{'
      write(1,*) 'COLOR = WHITE'
      write(1,*) '}'
      write(1,*) '  BOUNDARY'
      write(1,*) '{'
      write(1,*) 'COLOR = CYAN'
      write(1,*) '}'
      write(1,*) '  VOLUMEMODE'
      write(1,*) '{'
      write(1,*) 'VOLUMEOBJECTSTOPLOT'
      write(1,*) '  {'
      write(1,*) '  SHOWISOSURFACES = NO'
      write(1,*) '  SHOWSLICES = NO'
      write(1,*) '  SHOWSTREAMTRACES = NO'
      write(1,*) '  }'
      write(1,*) 'SURFACESTOPLOT = KPLANES'
      write(1,*) 'POINTSTOPLOT = SURFACESONLY'
      write(1,*) '}'
      write(1,*) '$!TWODAXIS '
      write(1,*) '  XVAR = 1'
      write(1,*) '  YVAR = 2'
      write(1,*) '$!VIEW FIT'
      write(1,*) '$!TWODAXIS '
      write(1,*) '  DEPXTOYRATIO = 1'
      write(1,*) '  AXISMODE = INDEPENDENT'
      write(1,*) '  XDETAIL'
      write(1,*) '{'
      write(1,*) 'RANGEMIN = 0.2'
      write(1,*) 'RANGEMAX = 5'
      write(1,*) 'GRSPACING = 1'
      write(1,*) '}'
      write(1,*) '    YDETAIL'
      write(1,*) '       {'
      write(1,*) '       RANGEMIN = 0'
      write(1,*) '    RANGEMAX = 0.1'
      write(1,*) '    GRSPACING = 0.01'
      write(1,*) '    }'
      write(1,*) '$!GLOBALISOSURFACE '
      write(1,*) '  ISOVALUE1 = 0.00162274146201'
      write(1,*) '  ISOVALUE2 = 0.00324549950227'
      write(1,*) '  ISOVALUE3 = 0.00486825754253'
      write(1,*) '$!FIELDLAYERS '
      write(1,*) '  SHOWMESH = NO'
      write(1,*) '  SHOWCONTOUR = YES'
      write(1,*) '   SHOWBOUNDARY = NO'
      write(1,*) '$!REMOVEVAR |LFDSFN1|'
      write(1,*) '$!SETSTYLEBASE CONFIG'

      close (unit=1) 

      END
